function cfg = config_base()

cfg.sim = struct( ...
    't0',               0, ...
    'dt_ptp',           0.1, ...
    'dt_orbital',       1, ...
    'sim_duration',     0.1, ...
    'min_los_duration', 1, ...
    'orbit_propagator', 'sgp4');

cfg.ptp = struct( ...
    'sync_interval',       1, ...
    'initial_time_offset', 0, ...
    'min_msg_interval',    1e-6, ...
    'verbose',             false);

cfg.exp.root = "results";

end
