function cfg = config_base()

cfg.sim = struct( ...
    'start_time', datetime(2025,11,05,0,0,0,'TimeZone','UTC'), ...
    't0',               0, ...
    'dt_ptp',           0.1, ...
    'dt_orbital',       1, ...
    'sim_duration',     0.6, ...
    'min_los_duration', 1, ...
    'orbit_propagator', 'two-body-keplerian', ...
    'use_interpolation', true, ...
    'carrier_frequency', 14e9);

cfg.ptp = struct( ...
    'sync_interval',       1, ...
    'initial_time_offset', 0, ...
    'min_msg_interval',    1e-6, ...
    'verbose',             false);

cfg.exp.root = "results";

end
