% Rubidium Atomic Clock (10 MHz CSAC-SA45)
function ox = ox_csac()

    f0 = 10e6;
    np = NoiseProfile(struct( ...
        'delta_f0', (rand() * 2 * 5e-4) - 5e-4, ...
        'alpha', (rand() * 2 * 3.15e-9) - 3.15e-9, ...
        'power_law_coeffs', [0, 0, 1.8e-19, 0, 2.0e-28], ...
        'timestamp_resolution', 0));
    ox = struct( ...
        'f0', f0, ...
        'np', np);
end