function ox = ox_perfect()
% Perfect oscillator — no noise, no drift, infinite timestamp precision.
    ox = struct( ...
        'f0',                   100e6, ...
        'delta_f0',             0, ...
        'alpha',                0, ...
        'h',                    zeros(1,5), ...
        'timestamp_resolution', 0);
end
